### ISSUE TITLE
マニュアル作成方法の検討

### ISSUE THREAD

**Issue by ssssota** [nanoFreaks/yobimori_developer_manumal#14]
## WHY

ref. #13

- gitbookが最新のnode.jsで動作しない
- [gitbook自体deprecated](https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning)

## WHAT

- [x] ドキュメント作成方法のリストアップ
  - バージョン管理されること
  - web上でも編集できること（非エンジニアも編集する可能性を鑑みて）
  - markdownで記述できること（形式・記法の統一）
- [x] 検討・決定

**Comment by ssssota** [comment]
> `gitbook serve`を実行する時に、`Node.js`の`version`によってはエラーを吐くことが分かりました。`Node.js`が新しすぎるとダメみたいです。
> 以下、参考にした記事です
> 
> - [gitbook install時にエラー](https://teratail.com/questions/279576)
> - [Node.js v12にアップデートするとgulp v4でもfs.jsで「ReferenceError: primordials is not defined」エラーが発生](https://hepokon365.hatenablog.com/entry/2019/10/31/022524)
> 
> `Node.js`自体のバージョン管理ツールである`n`を使って、`Node.js`の`version`を`10.23.0`まで下げると、ローカルでサーバーを立てられました。この事はマニュアルに記載するべきと思います(僕がハマったエラーなので、いつかのタイミングで僕が追加するべきかと)。

_Originally posted by @o-xian999 in https://github.com/nanoFreaks/yobimori_developer_manumal/issues/13#issuecomment-735340165_

> versionが新しすぎるとエラーというのは問題ですね、、
> [gitbook公式github](https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning)を見ると、最近は頻繁にアップデートがされておらず、[GitBook.com](https://www.gitbook.com/)に力を入れているようですね。
> 
> マニュアルの作成方法が現在の方法でいいのか、検討するのもいいかもしれない。

_Originally posted by @shun012526 in https://github.com/nanoFreaks/yobimori_developer_manumal/issues/13#issuecomment-735359203_

**Comment by ssssota** [comment]
- [GitHub Wiki](https://docs.github.com/ja/free-pro-team@latest/github/building-a-strong-community/documenting-your-project-with-wikis)
- [Notion](https://www.notion.so/d0abcaabdffc456994da6cec31fe9a68)
- [GitBook](https://www.gitbook.com/)
- [HackMD](https://hackmd.io/)
- 各リポジトリ`/docs`で管理

**Comment by shun012526** [comment]
## Notion
### メリット
- web上で容易に編集できる。
- リアルタイムで反映されるので作成スピードが早まる。
- マークダウンの知識がなくても、記述できる。もちろんマークダウンで記述できる。
- バージョン管理が可能（有料版にアップグレードする必要がある）

### デメリット
- ユーザの管理が必要。第３者がグループに入らないよう、メールドメインなどでの制限が必要
- リアルタイムで反映されるので、チェック機能が怠りやすい。（誤った情報が広まる可能性あり）
- ブランチ切ることができない

**Comment by ssssota** [comment]
開発者が全体を把握するために読むものなのか
コードを読み書きするために読むものなのか
という話があって
前者なら現状だと粒度が細かすぎる気がしていて
後者ならもっと各リポジトリと密な関係性を保った方がいいと思うんですよね
この辺りいかがでしょう。

**Comment by shun012526** [comment]
今回のマニュアル作りの目的としては前者に相当します。
どのような機能があるのかをまとめてもらい、全員が把握した上で１２月中旬〜のサービス開始に臨む事が目的です。

後者については宗太郎がいう通りに、リポジトリ内のWikiなど（ほかの提案があれば教えてください）でまとめたりするのがいいと思います

**Comment by ssssota** [comment]
- onedrive + office
- GitHub Pages + Jekyll
- MkDocs + GitHub Pages (+ GitHub Actions)

PRで承認しないと更新できないのはメリットですよねぇ…

**Comment by ssssota** [comment]
## GitHub Wiki

### pros

- git
  - ブランチ
  - 変更履歴
- webからも編集できる
- github組み込みなので導線が明らか

### cons

- Pull Requestが作成できない
- 画像も管理するにはちょっと面倒
  - リポジトリに画像を追加する必要がある

**Comment by ssssota** [comment]
## リポジトリ`/docs`で管理

### pros

- リポジトリ本体で管理
  - gitの機能が使える
  - githubの機能が使える
    - issus,pr
- webでも編集できる

### cons

- 導線の確保に気を遣わないとわかりにくくなりうる
- 画像を貼るのが少しめんどくさい

**Comment by ssssota** [comment]
## GitHub Pages

### pros

- gitの機能が使える
- githubの機能が使える
  - issue,pr
- urlが割り当てられる e.g. `https://nanofreaks.github.io/yobimori_developer_manual/`

### cons

- プライベートリポジトリでもurlを知っていれば閲覧できる（ある意味pros?）
- 画像を貼るには…
- デザインがjekyll依存?

**Comment by ssssota** [comment]
初動notionでスピード重視で作って、git使うどれかに移行するのがベストプラクティスな感があるな。

gitのどれ使うかに関しては、公開範囲によって使い分けるのがいいかなと思った
github wikiはprがないのであんまメリットがない
/docsとpagesは、pagesで一般公開+整形表示するかという違いなので本質は変わらない

**Comment by shun012526** [comment]
@ssssota 
調査ありがとう！
昨日・一昨日動けておらず、すみません

@ssssota @o-xian999 
全体を把握するのが第一の目的なので、まずはnotionで作成しましょうか
notionでマニュアル作成時のフォーマットだけ急ぎ作成するので、確認をよろしくおねがいします

**Comment by ssssota** [comment]
デベロッパーが最初に呼ぶべき文書はNotionでまとめる方針になった。
これは、

- デベロッパー以外が読む可能性があること
- HackMDでとりあえず作ってまあこんなもんやろってなった

などがある。

細かい粒度の話は各リポジトリ`/docs`ディレクトリで管理することとする。
これは、

- ドキュメントとコードの距離を近づけること
- PRを作成して修正させる

などの理由による。
